In [14]:
import pandas as pd
import plotly.express as px

In [24]:
url = "https://raw.githubusercontent.com/kamyczuram/Projects/main/Data/synthetic_dataset.csv"
df = pd.read_csv(url)

In [25]:
df.head()

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4188 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [27]:
df.describe()

             Price       Rating     Discount
count  4188.000000  2312.000000  3970.000000
mean   5016.970630     3.038293    24.516625
std    2839.984813     1.143074    14.347164
min     102.000000     1.000366     0.000000
25%    2628.250000     2.069490    12.000000
50%    4996.500000     3.082060    25.000000
75%    7418.000000     4.008620    37.000000
max    9999.000000     4.997818    49.000000

In [28]:
df.value_counts("Category")

Category
C    425
D    408
A    403
B    378
Name: count, dtype: int64

In [29]:
df.value_counts("Stock")

Stock
In Stock        1513
Out of Stock    1497
Name: count, dtype: int64

In [30]:
df.isnull().sum()

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

In [31]:
fig = px.histogram(df,
                   x="Price",
                   color="Category",
                   facet_col="Category",
                   marginal="box",
                   nbins=30,
                   opacity=0.75)

fig.update_layout(height=600, width=1000)
fig.show()

In [ ]:
from google.colab import drive
from getpass import getpass
import os

drive.mount('/content/drive')
#os.environ['GITHUB_TOKEN'] = getpass('Wklej swój GitHub Personal Access Token: ')

GITHUB_USER = "kamyczuram"

!git config --global user.email "KamyczuraM@gmail.com"
!git config --global user.name "{GITHUB_USER}"

!git clone https://{GITHUB_USER}:${{GITHUB_TOKEN}}@github.com/{GITHUB_USER}/Projects.git

notebook_path = "/content/drive/My Drive/Colab Notebooks/DS/EDA_FE_XGBOOST_Retail_Product_Dataset.ipynb"
target_dir = "Projects/EDA_FE_XGBOOST_Retail_Product_Dataset"
target_path = f"{target_dir}/EDA_FE_XGBOOST_Retail_Product_Dataset.ipynb"

os.makedirs(target_dir, exist_ok=True)

!cp "{notebook_path}" "{target_path}"

!cd Projects && git add EDA_FE_XGBOOST_Retail_Product_Dataset/EDA_FE_XGBOOST_Retail_Product_Dataset.ipynb
!cd Projects && git commit -m "Aktualizacja notebooka z Colaba"
!cd Projects && git push