In [1]:
import pandas as pd
import plotly.express as px

In [2]:
url = "https://raw.githubusercontent.com/kamyczuram/Projects/main/Data/synthetic_dataset.csv"
df = pd.read_csv(url)

In [3]:
df.head()

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4188 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [5]:
df.describe()

             Price       Rating     Discount
count  4188.000000  2312.000000  3970.000000
mean   5016.970630     3.038293    24.516625
std    2839.984813     1.143074    14.347164
min     102.000000     1.000366     0.000000
25%    2628.250000     2.069490    12.000000
50%    4996.500000     3.082060    25.000000
75%    7418.000000     4.008620    37.000000
max    9999.000000     4.997818    49.000000

In [6]:
df.value_counts("Category")

Category
C    425
D    408
A    403
B    378
Name: count, dtype: int64

In [7]:
df.value_counts("Stock")

Stock
In Stock        1513
Out of Stock    1497
Name: count, dtype: int64

In [8]:
df.isnull().sum()

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

In [9]:
len(df.dropna()) / len(df)

0.12379642365887207

In [10]:
fig = px.histogram(df,
                   x="Price",
                   color="Category",
                   facet_col="Category",
                   marginal="box",
                   nbins=30,
                   opacity=0.75)

fig.update_layout(height=600, width=1000)
fig.show()

In [11]:
fig = px.histogram(df,
                   x="Price",
                   color="Stock",
                   facet_col="Stock",
                   marginal="box",
                   nbins=30,
                   opacity=0.75)

fig.update_layout(height=600, width=1000)
fig.show()

In [12]:
numeric_df = df.select_dtypes(include='number')
correlation_matrix = numeric_df.corr()
print(correlation_matrix)

             Price    Rating  Discount
Price     1.000000  0.021099  0.009300
Rating    0.021099  1.000000  0.015028
Discount  0.009300  0.015028  1.000000

In [13]:
categorical_cols = ['Stock', 'Category']
numeric_cols = df.select_dtypes(include='number').columns

for cat_col in categorical_cols:
    print(f"\n Grouped by: {cat_col}")
    grouped = df.groupby(cat_col)[numeric_cols].agg(['mean', 'median'])
    print(grouped)

 Grouped by: Stock
                    Price            Rating             Discount
                     mean  median      mean    median       mean median
Stock
In Stock      5042.933975  5014.5  3.014508  2.974713  24.922525   25.0
Out of Stock  5006.118513  4999.5  3.067492  3.120587  24.142751   24.0

 Grouped by: Category
                Price            Rating             Discount
                 mean  median      mean    median       mean median
Category
A         4782.910026  4745.0  3.089706  3.029522  25.403846   26.0
B         5410.330623  5499.0  3.098575  3.245094  24.016949   24.5
C         5086.802500  4954.5  2.878008  2.845403  24.311688   25.0
D         5032.468672  5031.0  3.116892  3.238450  25.346369   26.0

In [14]:
missing_mask = df.isnull().astype(int)

In [15]:
num_df = df.select_dtypes(include='number')

In [16]:
combined_df = pd.concat([missing_mask, num_df], axis=1)

In [17]:
combined_df.corr()

,Category,Price,Rating,Stock,Discount,Price,Rating,Discount
Category,1.000000,0.017912,0.010968,0.011559,-0.013207,-0.015349,-0.002778,-0.013261
Price,0.017912,1.000000,0.012265,-0.025156,-0.010801,NaN,-0.002215,0.016719
Rating,0.010968,0.012265,1.000000,0.014504,-0.003577,-0.009624,NaN,0.003833
Stock,0.011559,-0.025156,0.014504,1.000000,0.011266,-0.004042,-0.002977,-0.002295
Discount,-0.013207,-0.010801,-0.003577,0.011266,1.000000,-0.005519,-0.026335,NaN
Price,-0.015349,NaN,-0.009624,-0.004042,-0.005519,1.000000,0.021099,0.009300
Rating,-0.002778,-0.002215,NaN,-0.002977,-0.026335,0.021099,1.000000,0.015028
Discount,-0.013261,0.016719,0.003833,-0.002295,NaN,0.009300,0.015028,1.000000

##Nothing interesting in this data..

In [ ]:
from google.colab import drive
from getpass import getpass
import os

drive.mount('/content/drive')
os.environ['GITHUB_TOKEN'] = getpass('Wklej swój GitHub Personal Access Token: ')

GITHUB_USER = "kamyczuram"

!git config --global user.email "KamyczuraM@gmail.com"
!git config --global user.name "{GITHUB_USER}"

!git clone https://{GITHUB_USER}:${{GITHUB_TOKEN}}@github.com/{GITHUB_USER}/Projects.git

notebook_path = "/content/drive/My Drive/Colab Notebooks/DS/EDA_FE_XGBOOST_Retail_Product_Dataset.ipynb"
target_dir = "Projects/EDA_FE_XGBOOST_Retail_Product_Dataset"
target_path = f"{target_dir}/EDA_FE_XGBOOST_Retail_Product_Dataset.ipynb"

os.makedirs(target_dir, exist_ok=True)

!cp "{notebook_path}" "{target_path}"

!cd Projects && git add EDA_FE_XGBOOST_Retail_Product_Dataset/EDA_FE_XGBOOST_Retail_Product_Dataset.ipynb
!cd Projects && git commit -m "Aktualizacja notebooka z Colaba"
!cd Projects && git push --force