In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
!git clone https://github.com/kamyczuram/Projects.git

Cloning into 'Projects'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (181/181), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 181 (delta 59), reused 165 (delta 49), pack-reused 0 (from 0)
Receiving objects: 100% (181/181), 5.53 MiB | 8.99 MiB/s, done.
Resolving deltas: 100% (59/59), done.
Filtering content: 100% (12/12), 138.69 MiB | 28.98 MiB/s, done.

In [5]:
%cd Projects
df = pd.read_csv('Data/store_sales/train.csv')
df_oil = pd.read_csv('Data/store_sales/oil.csv')
df_holiday = pd.read_csv('Data/store_sales/holidays_events.csv')
df_stores = pd.read_csv('Data/store_sales/stores.csv')
df_transactions = pd.read_csv('Data/store_sales/transactions.csv')
sample = pd.read_csv('Data/store_sales/sample_submission.csv')

[Errno 2] No such file or directory: 'Projects'
/content/Projects

In [8]:
df_test = pd.read_csv('Data/store_sales/test.csv')
df_test

            id        date  store_nbr                      family  onpromotion
0      3000888  2017-08-16          1                  AUTOMOTIVE            0
1      3000889  2017-08-16          1                   BABY CARE            0
2      3000890  2017-08-16          1                      BEAUTY            2
3      3000891  2017-08-16          1                   BEVERAGES           20
4      3000892  2017-08-16          1                       BOOKS            0
...        ...         ...        ...                         ...          ...
28507  3029395  2017-08-31          9                     POULTRY            1
28508  3029396  2017-08-31          9              PREPARED FOODS            0
28509  3029397  2017-08-31          9                     PRODUCE            1
28510  3029398  2017-08-31          9  SCHOOL AND OFFICE SUPPLIES            9
28511  3029399  2017-08-31          9                     SEAFOOD            0

[28512 rows x 5 columns]

In [9]:
sample

            id  sales
0      3000888    0.0
1      3000889    0.0
2      3000890    0.0
3      3000891    0.0
4      3000892    0.0
...        ...    ...
28507  3029395    0.0
28508  3029396    0.0
28509  3029397    0.0
28510  3029398    0.0
28511  3029399    0.0

[28512 rows x 2 columns]

In [4]:
df

,id,date,store_nbr,family,sales,onpromotion
0,0,2013-01-01,1,AUTOMOTIVE,0.000,0
1,1,2013-01-01,1,BABY CARE,0.000,0
2,2,2013-01-01,1,BEAUTY,0.000,0
3,3,2013-01-01,1,BEVERAGES,0.000,0
4,4,2013-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
3000883,3000883,2017-08-15,9,POULTRY,438.133,0
3000884,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
3000885,3000885,2017-08-15,9,PRODUCE,2419.729,148
3000886,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
3000887,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [18]:
df[(df['family'] =='BEAUTY') & (df['store_nbr'] == 1)]

              id        date  store_nbr  family  sales  onpromotion
2              2  2013-01-01          1  BEAUTY    0.0            0
1784        1784  2013-01-02          1  BEAUTY    2.0            0
3566        3566  2013-01-03          1  BEAUTY    0.0            0
5348        5348  2013-01-04          1  BEAUTY    3.0            0
7130        7130  2013-01-05          1  BEAUTY    3.0            0
...          ...         ...        ...     ...    ...          ...
2991980  2991980  2017-08-11          1  BEAUTY    1.0            1
2993762  2993762  2017-08-12          1  BEAUTY    3.0            1
2995544  2995544  2017-08-13          1  BEAUTY    1.0            0
2997326  2997326  2017-08-14          1  BEAUTY    6.0            1
2999108  2999108  2017-08-15          1  BEAUTY    4.0            1

[1684 rows x 6 columns]

In [19]:
plt = px.line(df[(df['family'] =='BEAUTY') & (df['store_nbr'] == 1)], x='date', y='sales')
plt.show()

In [20]:
df['store_nbr'].unique()

array([ 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  2, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29,  3, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,  4,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49,  5, 50, 51, 52, 53, 54,  6,
        7,  8,  9])

In [25]:
for i in range(1,6):
  plt = px.line(df[(df['family'] =='BOOKS') & (df['store_nbr'] == i)], x='date', y='sales')
  plt.show()

In [ ]:
from google.colab import drive
from getpass import getpass
import os

drive.mount('/content/drive')
os.environ['GITHUB_TOKEN'] = getpass('Wklej swój GitHub Personal Access Token: ')

GITHUB_USER = "kamyczuram"
file_name = "Store_Sales_Arima_Sarima"

!git config --global user.email "KamyczuraM@gmail.com"
!git config --global user.name "{GITHUB_USER}"

!rm -rf Projects
!git clone https://{GITHUB_USER}:${{GITHUB_TOKEN}}@github.com/{GITHUB_USER}/Projects.git

notebook_path = f"/content/drive/My Drive/Colab Notebooks/DS/{file_name}.ipynb"
target_dir = f"Projects/{file_name}"
target_path = f"{target_dir}/{file_name}.ipynb"

os.makedirs(target_dir, exist_ok=True)

!cp "{notebook_path}" "{target_path}"

!cd Projects && git add {file_name}/{file_name}.ipynb
!cd Projects && git commit -m "Aktualizacja notebooka z Colaba"
!cd Projects && git pull origin main --rebase
!cd Projects && git push

Mounted at /content/drive