In [1]:
import pandas as pd
import plotly.express as px
import statsmodels.api as sm

In [2]:
url = "https://raw.githubusercontent.com/kamyczuram/Projects/main/Data"
df = pd.read_csv(url + '/house_train.csv')
df_test = pd.read_csv(url + '/house_test.csv')
df_sample_submission = pd.read_csv(url + '/house_sample_submission.csv')

In [3]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
df_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [6]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [7]:
df.isnull().sum()[df.isnull().sum() > 0]

LotFrontage      259
Alley           1369
MasVnrType       872
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

In [8]:
corr_matrix = df.select_dtypes(include='number').corr()

In [9]:
fig = px.imshow(corr_matrix,
                labels=dict(color="Correlation"),
                x=corr_matrix.columns,
                y=corr_matrix.index,
                title="Heatmap of Correlation Matrix")
fig.update_layout(width=800, height=800)
fig.show()

In [10]:
df.sample(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
721,722,120,RM,NaN,4426,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,143000
956,957,160,RM,24.0,1300,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,5,2009,WD,Normal,124000
1168,1169,70,RL,120.0,13728,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,235000
354,355,50,RL,60.0,8400,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,140000
826,827,45,RM,50.0,6130,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,109500
989,990,60,FV,65.0,8125,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,New,Partial,197000
1135,1136,30,RM,60.0,6180,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,102000
716,717,70,RM,60.0,10800,Pave,Grvl,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,7,2007,WD,Normal,159500
803,804,60,RL,107.0,13891,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2009,New,Partial,582933
527,528,60,RL,67.0,14948,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,New,Partial,446261

In [11]:
none_cols = [
    'Alley', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
    'BsmtFinType1', 'BsmtFinType2', 'FireplaceQu',
    'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
    'PoolQC', 'Fence', 'MiscFeature', 'MasVnrType'
]

for col in none_cols:
    df[col] = df[col].fillna("None")

df['MasVnrArea'] = df.apply(
    lambda row: 0.0 if row['MasVnrType'] == 'None' else row['MasVnrArea'],
    axis=1
)

df['GarageYrBlt'] = df.apply(
    lambda row: 0.0 if row['GarageType'] == 'None' else row['GarageYrBlt'],
    axis=1
)

df['Electrical'] = df['Electrical'].fillna('Unknown')

In [12]:
df.sample(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
871,872,60,RL,70.0,8750,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,6,2010,WD,Normal,200500
1209,1210,20,RL,85.0,10182,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,5,2006,New,Partial,290000
1306,1307,120,RL,48.0,6955,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,9,2006,New,Partial,202500
295,296,80,RL,37.0,7937,Pave,None,IR1,Lvl,AllPub,...,0,None,GdPrv,None,0,3,2006,WD,Normal,142500
858,859,20,RL,80.0,10400,Pave,None,Reg,Lvl,AllPub,...,0,None,MnPrv,None,0,6,2009,WD,Family,152000
530,531,80,RL,85.0,10200,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,8,2008,WD,Abnorml,175000
797,798,20,RL,57.0,7677,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,4,2008,WD,Abnorml,110000
1370,1371,50,RL,90.0,5400,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,10,2009,WD,Normal,105000
839,840,50,RL,70.0,11767,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,5,2008,WD,Normal,130500
443,444,120,RL,53.0,3922,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,6,2007,New,Partial,172500

In [13]:
df.isnull().sum()[df.isnull().sum() > 0]

LotFrontage    259
dtype: int64

In [14]:
corr_matrix['LotFrontage'][abs(corr_matrix['LotFrontage']) > 0.3]

MSSubClass     -0.386347
LotFrontage     1.000000
LotArea         0.426095
TotalBsmtSF     0.392075
1stFlrSF        0.457181
GrLivArea       0.402797
TotRmsAbvGrd    0.352096
GarageArea      0.344997
SalePrice       0.351799
Name: LotFrontage, dtype: float64

In [15]:
target = 'LotFrontage'

df_temp = df.drop(columns=[target])
df_temp = pd.get_dummies(df_temp, drop_first=True)
df_temp = df_temp.astype(float)
df_temp[target] = df[target]

features = df_temp.columns.drop(target).tolist()

df_clean = df_temp.dropna()
df_Nan = df_temp.loc[~df_temp.index.isin(df_clean.index)]

X = df_clean[features]
y = df_clean[target]


X = sm.add_constant(X)

model = sm.OLS(y, X).fit()

X_nan = df_Nan[features]
X_nan = sm.add_constant(X_nan)
pred_for_Nan = model.predict(X_nan)


df_filled = df.copy()

df_filled.loc[pred_for_Nan.index, target] = pred_for_Nan

In [16]:
df_filled.isnull().sum()[df.isnull().sum() > 0]

LotFrontage    0
dtype: int64

In [18]:
from google.colab import drive
from getpass import getpass
import os

drive.mount('/content/drive')
os.environ['GITHUB_TOKEN'] = getpass('Wklej swój GitHub Personal Access Token: ')

GITHUB_USER = "kamyczuram"
file_name = "House_Prices_XGBOOST"

!git config --global user.email "KamyczuraM@gmail.com"
!git config --global user.name "{GITHUB_USER}"

!git clone https://{GITHUB_USER}:${{GITHUB_TOKEN}}@github.com/{GITHUB_USER}/Projects.git

notebook_path = f"/content/drive/My Drive/Colab Notebooks/DS/{file_name}.ipynb"
target_dir = f"Projects/{file_name}"
target_path = f"{target_dir}/{file_name}.ipynb"

os.makedirs(target_dir, exist_ok=True)

!cp "{notebook_path}" "{target_path}"

!cd Projects && git add {file_name}/{file_name}.ipynb
!cd Projects && git commit -m "Aktualizacja notebooka z Colaba"
!cd Projects && git pull origin main --rebase
!cd Projects && git push

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Wklej swój GitHub Personal Access Token: ··········
fatal: destination path 'Projects' already exists and is not an empty directory.
[main 808ddf7] Aktualizacja notebooka z Colaba
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite House_Prices_XGBOOST/House_Prices_XGBOOST.ipynb (97%)
warning: redirecting to https://github.com/kamyczuram/Projects.git/
From https://github.com/kamyczuram/Projects
 * branch            main       -> FETCH_HEAD
Current branch main is up to date.
remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/kamyczuram/Projects.git/'