In [24]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.4.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.16.4-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.14.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.3)
Downloading optuna-4.4.0-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.9/395.9 kB 13.4 MB/s eta 0:00:00
Downloading alembic-1.16.4-py3-none-any.whl (247 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.0/247.0 kB 19.0 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.16.4 colorlog-6.9.0 optuna-4.4.0

In [25]:
import pandas as pd
import plotly.express as px
import statsmodels.api as sm
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import optuna

In [2]:
url = "https://raw.githubusercontent.com/kamyczuram/Projects/main/Data"
df = pd.read_csv(url + '/house_train.csv')
df_test = pd.read_csv(url + '/house_test.csv')
df_sample_submission = pd.read_csv(url + '/house_sample_submission.csv')

In [3]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
df_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [6]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [7]:
df.isnull().sum()[df.isnull().sum() > 0]

LotFrontage      259
Alley           1369
MasVnrType       872
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

In [8]:
corr_matrix = df.select_dtypes(include='number').corr()

In [9]:
fig = px.imshow(corr_matrix,
                labels=dict(color="Correlation"),
                x=corr_matrix.columns,
                y=corr_matrix.index,
                title="Heatmap of Correlation Matrix")
fig.update_layout(width=800, height=800)
fig.show()

In [10]:
df.sample(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
31,32,20,RL,NaN,8544,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2008,WD,Normal,149350
601,602,50,RM,50.0,9000,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,141000
1009,1010,50,RL,60.0,6000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,102000
1224,1225,60,RL,60.0,15384,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,184000
441,442,90,RL,92.0,12108,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,118000
301,302,60,RL,66.0,16226,Pave,NaN,IR3,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,267000
1395,1396,60,RL,88.0,12665,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2007,WD,Normal,281213
648,649,60,RL,70.0,7700,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,155000
288,289,20,RL,NaN,9819,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,122000
1452,1453,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,145000

In [11]:
none_cols = [
    'Alley', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
    'BsmtFinType1', 'BsmtFinType2', 'FireplaceQu',
    'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
    'PoolQC', 'Fence', 'MiscFeature', 'MasVnrType'
]

for col in none_cols:
    df[col] = df[col].fillna("None")

df['MasVnrArea'] = df.apply(
    lambda row: 0.0 if row['MasVnrType'] == 'None' else row['MasVnrArea'],
    axis=1
)

df['GarageYrBlt'] = df.apply(
    lambda row: 0.0 if row['GarageType'] == 'None' else row['GarageYrBlt'],
    axis=1
)

df['Electrical'] = df['Electrical'].fillna('Unknown')

In [12]:
df.sample(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1105,1106,60,RL,98.0,12256,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,4,2010,WD,Normal,325000
927,928,60,RL,NaN,9900,Pave,None,Reg,Lvl,AllPub,...,0,None,GdPrv,None,0,4,2008,WD,Normal,176000
861,862,190,RL,75.0,11625,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,4,2010,WD,Normal,131500
629,630,80,RL,82.0,9020,Pave,None,Reg,Lvl,AllPub,...,0,None,GdPrv,None,0,6,2008,WD,Normal,168500
1164,1165,80,RL,NaN,16157,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,6,2007,WD,Normal,194000
428,429,20,RL,64.0,6762,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,9,2007,New,Partial,195400
176,177,60,RL,97.0,10029,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,9,2007,WD,Normal,211000
415,416,20,RL,73.0,8899,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,8,2007,New,Partial,181134
516,517,80,RL,NaN,10448,Pave,None,IR1,Lvl,AllPub,...,0,None,GdPrv,None,0,8,2009,COD,Abnorml,158000
1362,1363,50,RL,NaN,12513,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,6,2009,WD,Normal,104900

In [13]:
df.isnull().sum()[df.isnull().sum() > 0]

LotFrontage    259
dtype: int64

In [14]:
corr_matrix['LotFrontage'][abs(corr_matrix['LotFrontage']) > 0.3]

MSSubClass     -0.386347
LotFrontage     1.000000
LotArea         0.426095
TotalBsmtSF     0.392075
1stFlrSF        0.457181
GrLivArea       0.402797
TotRmsAbvGrd    0.352096
GarageArea      0.344997
SalePrice       0.351799
Name: LotFrontage, dtype: float64

In [15]:
target = 'LotFrontage'

df_temp = df.drop(columns=[target])
df_temp = pd.get_dummies(df_temp, drop_first=True)
df_temp = df_temp.astype(float)
df_temp[target] = df[target]

features = df_temp.columns.drop(target).tolist()

df_clean = df_temp.dropna()
df_Nan = df_temp.loc[~df_temp.index.isin(df_clean.index)]

X = df_clean[features]
y = df_clean[target]


X = sm.add_constant(X)

model = sm.OLS(y, X).fit()

X_nan = df_Nan[features]
X_nan = sm.add_constant(X_nan)
pred_for_Nan = model.predict(X_nan)


df_filled = df.copy()

df_filled.loc[pred_for_Nan.index, target] = pred_for_Nan

In [16]:
df_filled.isnull().sum()[df.isnull().sum() > 0]

LotFrontage    0
dtype: int64

In [19]:

X = df_filled.drop(columns=['SalePrice'])
y = df_filled['SalePrice']


X = pd.get_dummies(X)
X = df_temp.astype(float)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=33)

model = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=33)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

MSE: 14177639.0
R²: 0.9977098107337952

In [21]:
df_filled['SalePrice'].mean()

np.float64(180921.19589041095)

In [28]:
def objective(trial):
    n_estimators = trial.suggest_int('n_estimators', 100, 1000, step=100)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.1, step=0.01)
    max_depth = trial.suggest_int('max_depth', 3, 10)
    subsample = trial.suggest_float('subsample', 0.5, 1.0, step=0.1)
    alpha = trial.suggest_float('alpha', 0.0, 1.0, step=0.1)

    model = xgb.XGBRegressor(
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        subsample=subsample,
        alpha=alpha,
        random_state=33
    )
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)

    return mse

In [29]:
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=20)

[I 2025-08-03 07:18:46,858] A new study created in memory with name: no-name-e1fa03d7-9cc0-4fdd-845d-86fa2b410fed
[I 2025-08-03 07:18:47,473] Trial 0 finished with value: 14874549.0 and parameters: {'n_estimators': 200, 'learning_rate': 0.09, 'max_depth': 3, 'subsample': 0.9, 'alpha': 0.8}. Best is trial 0 with value: 14874549.0.
[I 2025-08-03 07:18:50,970] Trial 1 finished with value: 13233261.0 and parameters: {'n_estimators': 500, 'learning_rate': 0.05, 'max_depth': 7, 'subsample': 0.9, 'alpha': 0.6000000000000001}. Best is trial 1 with value: 13233261.0.
[I 2025-08-03 07:19:02,583] Trial 2 finished with value: 12009863.0 and parameters: {'n_estimators': 800, 'learning_rate': 0.060000000000000005, 'max_depth': 8, 'subsample': 0.7, 'alpha': 0.30000000000000004}. Best is trial 2 with value: 12009863.0.
[I 2025-08-03 07:19:05,873] Trial 3 finished with value: 11887926.0 and parameters: {'n_estimators': 800, 'learning_rate': 0.09, 'max_depth': 5, 'subsample': 0.9, 'alpha': 0.7000000000000001}. Best is trial 3 with value: 11887926.0.
[I 2025-08-03 07:19:07,832] Trial 4 finished with value: 11177654.0 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04, 'max_depth': 3, 'subsample': 0.7, 'alpha': 0.7000000000000001}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:19:30,547] Trial 5 finished with value: 11276213.0 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09, 'max_depth': 9, 'subsample': 0.8, 'alpha': 0.8}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:19:36,743] Trial 6 finished with value: 12086001.0 and parameters: {'n_estimators': 900, 'learning_rate': 0.08, 'max_depth': 7, 'subsample': 0.5, 'alpha': 0.30000000000000004}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:19:46,473] Trial 7 finished with value: 14505740.0 and parameters: {'n_estimators': 800, 'learning_rate': 0.060000000000000005, 'max_depth': 8, 'subsample': 0.6, 'alpha': 0.0}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:19:58,542] Trial 8 finished with value: 11752571.0 and parameters: {'n_estimators': 900, 'learning_rate': 0.08, 'max_depth': 7, 'subsample': 0.6, 'alpha': 0.9}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:02,989] Trial 9 finished with value: 13425136.0 and parameters: {'n_estimators': 600, 'learning_rate': 0.060000000000000005, 'max_depth': 7, 'subsample': 0.8, 'alpha': 0.9}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:03,325] Trial 10 finished with value: 1026823232.0 and parameters: {'n_estimators': 100, 'learning_rate': 0.01, 'max_depth': 3, 'subsample': 1.0, 'alpha': 0.4}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:16,749] Trial 11 finished with value: 13983598.0 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 10, 'subsample': 0.7, 'alpha': 1.0}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:26,631] Trial 12 finished with value: 12706731.0 and parameters: {'n_estimators': 600, 'learning_rate': 0.04, 'max_depth': 10, 'subsample': 0.8, 'alpha': 0.6000000000000001}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:30,030] Trial 13 finished with value: 15457061.0 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'subsample': 0.7, 'alpha': 0.7000000000000001}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:31,508] Trial 14 finished with value: 16233339.0 and parameters: {'n_estimators': 400, 'learning_rate': 0.09999999999999999, 'max_depth': 5, 'subsample': 0.6, 'alpha': 0.5}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:41,699] Trial 15 finished with value: 12123982.0 and parameters: {'n_estimators': 700, 'learning_rate': 0.04, 'max_depth': 9, 'subsample': 0.8, 'alpha': 1.0}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:44,532] Trial 16 finished with value: 12834407.0 and parameters: {'n_estimators': 1000, 'learning_rate': 0.06999999999999999, 'max_depth': 4, 'subsample': 0.5, 'alpha': 0.8}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:48,604] Trial 17 finished with value: 12247680.0 and parameters: {'n_estimators': 400, 'learning_rate': 0.04, 'max_depth': 9, 'subsample': 1.0, 'alpha': 0.0}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:56,935] Trial 18 finished with value: 15837389.0 and parameters: {'n_estimators': 900, 'learning_rate': 0.09999999999999999, 'max_depth': 6, 'subsample': 0.7, 'alpha': 0.6000000000000001}. Best is trial 4 with value: 11177654.0.
[I 2025-08-03 07:20:58,698] Trial 19 finished with value: 14849927.0 and parameters: {'n_estimators': 700, 'learning_rate': 0.02, 'max_depth': 4, 'subsample': 0.8, 'alpha': 0.8}. Best is trial 4 with value: 11177654.0.

In [30]:
best_params = study.best_params
best_model = xgb.XGBRegressor(**best_params, random_state=33)
best_model.fit(X_train, y_train)

y_pred = best_model.predict(X_test)
print("MSE:", mean_squared_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

MSE: 11177654.0
R²: 0.9981944561004639

In [ ]:
from google.colab import drive
from getpass import getpass
import os

drive.mount('/content/drive')
os.environ['GITHUB_TOKEN'] = getpass('Wklej swój GitHub Personal Access Token: ')

GITHUB_USER = "kamyczuram"
file_name = "House_Prices_XGBOOST"

!git config --global user.email "KamyczuraM@gmail.com"
!git config --global user.name "{GITHUB_USER}"

!rm -rf Projects
!git clone https://{GITHUB_USER}:${{GITHUB_TOKEN}}@github.com/{GITHUB_USER}/Projects.git

notebook_path = f"/content/drive/My Drive/Colab Notebooks/DS/{file_name}.ipynb"
target_dir = f"Projects/{file_name}"
target_path = f"{target_dir}/{file_name}.ipynb"

os.makedirs(target_dir, exist_ok=True)

!cp "{notebook_path}" "{target_path}"

!cd Projects && git add {file_name}/{file_name}.ipynb
!cd Projects && git commit -m "Aktualizacja notebooka z Colaba"
!cd Projects && git pull origin main --rebase
!cd Projects && git push

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).